/* Auto-generated by the build process. Do not edit manually. */
#ifndef HTTP_SERVER_H
#define HTTP_SERVER_H

#include "file_registry.h"

/* Pre-inflate and cache the large JS entries so the first AppCache request
 * never pays the slow byte-at-a-time puff cost on the PS5. Called once after
 * the MHD daemon starts, before the browser begins caching. */
void pre_inflate_js_files(void);

#endif /* HTTP_SERVER_H */
