#pragma once

/* Base version of the WebKit Autoloader (WKAL) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching WKALI installer build. */
#define WKAL_VERSION "0.7.6"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/wkali_version.h */
#include "wkali_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template).
 * Distinct from the original WebKit Autoloader (18181) so both can coexist
 * on the same console without touching each other's AppCache origin. */
#define WKALI_PORT 18182

/* Title ID of the installed homescreen app ("L92 WebKit Autoloader").
 * PS5 title IDs MUST follow the pattern XXXX00000 (4 letters + 5 digits);
 * anything else installs but is silently hidden from the homescreen.
 * "LWAL00001" keeps the 4-letters+5-digits form and stays distinct from
 * the original WebKit Autoloader (WKAL00001) so both apps coexist. */
#define WKAL_TITLE_ID "LWAL00001"

/* Process identity — used to kill stale installer instances on startup.
 * Distinct from the original "wkali.elf" so the two installers never
 * terminate each other's processes if both are on the console. */
#define WKALI_THREAD_NAME "l92wkali.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_CLEAR_WEBKIT_DATA "/clear-webkit-data"
#define ROUTE_EXIT "/exit"

/* Logging (implementation in log.c) */
void wkali_log(const char *fmt, ...);
size_t wkali_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void wkali_log_wakeup(void);

/* Offline network bring-up (implementation in net_offline.c): guarantees at
 * least one interface has an IPv4 address so the Relapse chain's KASLR leak
 * (routing socket) works with Wi-Fi off / no cable connected. */
int wkali_ensure_interface_address(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
