#pragma once

/* Base version of the WebKit Autoloader (WKAL) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching WKALI installer build. */
#define WKAL_VERSION "0.6.2"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/wkali_version.h */
#include "wkali_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template).
 * Distinct from the original WebKit Autoloader (18181) so both can coexist
 * on the same console without touching each other's AppCache origin. */
#define WKALI_PORT 18182

/* Title ID of the installed homescreen app ("L92 WebKit Autoloader").
 * Distinct from the original WKAL00001 so installing this version never
 * overwrites an existing WebKit Autoloader app on the console. */
#define WKAL_TITLE_ID "L92WKAL01"

/* Process identity — used to kill stale installer instances on startup.
 * Distinct from the original "wkali.elf" so the two installers never
 * terminate each other's processes if both are on the console. */
#define WKALI_THREAD_NAME "l92wkali.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_CLEAR_WEBKIT_DATA "/clear-webkit-data"
#define ROUTE_EXIT "/exit"

/* Logging (implementation in log.c) */
void wkali_log(const char *fmt, ...);
size_t wkali_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void wkali_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
